server:
  port : 9090

spring: 
  profiles: 
    active: local

#local 환경
---  
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hrdtest?useSSL=false&serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: S017335
    password: qkrehdrb1!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: Hikari-pool
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        hbm2ddl.auto: update
    open-in-view: false
    show-sql: true
#  redis:
#    host: localhost
#    port: 6379

logging:
  level:
    org.hibernate.type: trace
